name: deploy to kafka broker

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout release
      uses: actions/checkout@v4

    - name: archive to tar.gz
      run: |
        tar -czf kafka-producer.tar.gz -C kafka-producer .


    - name: AWS configure credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET_KEY }}
        aws-region: ap-northeast-2

    - name: upload to S3
      run: |
        aws s3 cp --region ap-northeast-2 kafka-producer.tar.gz \
        s3://datalake-actions-deploy-nayun/kafka-producer/kafka-producer.tar.gz

    - name: deploy with AWS CodeDeploy
      run: |
        # ✅ 여러 줄 명령은 YAML 문법상 `|` 로 감싸야 함
        aws deploy create-deployment \
          --application-name datalake-deploy \
          --deployment-group-name kafka-deploy \
          --s3-location bucket=datalake-actions-deploy-nayun,key=kafka-producer/kafka-producer.tar.gz,bundleType=tgz \
          --region ap-northeast-2
#제발제랍라자!