version: 0.0
os: linux

files:
  - source: /
    destination: /src/kafka-producer
    overwrite: yes

file_exists_behavior: OVERWRITE

permissions:
  - object: /src/kafka-producer
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  BeforeInstall:
    - location: deploy/before_install.sh
      timeout: 60
      runas: ubuntu

  AfterInstall:
    - location: deploy/after_install.sh
      timeout: 300
      runas: ubuntu

  ApplicationStart:
    - location: deploy/application_start.sh
      timeout: 300
      runas: ubuntu

  ValidateService:
    - location: deploy/validate.sh
      timeout: 60
      runas: ubuntu
