name: deploy to kafka broker

on:
  # 어떤 이벤트에서 이 workflow를 실행할지 정의
  # master 브랜치에 push 발생 시 실행 + 수동 실행(workflow_dispatch) 가능
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  # build 라는 이름의 job 정의
  build:
    # GitHub에서 제공하는 Ubuntu 최신 환경에서 실행
    runs-on: ubuntu-latest

    steps:
    - name: checkout release
      # actions/checkout은 현재 레포지토리 코드를 runner 서버로 가져옴
      uses: actions/checkout@v4

    - name: archive to tar.gz
      # 현재 디렉토리 전체를 압축 (appspec.yml이 루트에 포함되도록!)
      run: tar cvfz ./kafka-producer.tar.gz ./*

    - name: AWS configure credentials
      # AWS CLI가 사용할 자격 증명을 GitHub Secrets에서 설정
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET_KEY }}
        aws-region: ap-northeast-2

    - name: upload to S3
      # 압축한 번들을 S3에 업로드
      run: aws s3 cp --region ap-northeast-2 ./kafka-producer.tar.gz s3://datalake-actions-deploy-nayun/kafka-producer/kafka-producer.tar.gz

    - name: deploy with AWS codeDeploy
      # CodeDeploy로 배포 생성
      run: |
        aws deploy create-deployment \
          --application-name datalake-deploy \
          --deployment-group-name kafka-deploy \
          --s3-location bucket=datalake-actions-deploy-nayun,bundleType=tar,key=kafka-producer/kafka-producer.tar.gz
